[package]
name = "sdl2_engine"
version = "0.1.0"
authors = ["Davide Giovannini <giovannini.davide90@gmail.com>"]
build = "build.rs"


[dependencies]
sdl2-sys = "*"
specs = "*"
gl = "0.6.0"

[dependencies.sdl2]
version = "0.28"
default-features = false
features = ["ttf","image","mixer"]
