[package]
name = "sdl2_engine"
version = "0.1.0"
authors = ["Davide Giovannini <giovannini.davide90@gmail.com>"]

[dependencies]

[dependencies.sdl2]
version = "0.28"
default-features = false
features = ["ttf","image","mixer"]
